# Generated by Django 4.2.11 on 2024-07-13 18:24

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('names', models.CharField(max_length=255)),
                ('lnames', models.CharField(max_length=255)),
                ('salt', models.CharField(blank=True, max_length=32)),
                ('password_hash', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('usermanager_object', django.db.models.manager.Manager()),
            ],
        ),
    ]
