# Generated by Django 5.0.6 on 2024-07-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='run',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
