# Generated by Django 5.0.6 on 2024-07-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_user_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lnames',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
