# Generated by Django 5.0.6 on 2024-07-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_alter_user_lnames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lnames',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='run',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True),
        ),
    ]
