# Generated by Django 5.0.6 on 2024-07-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_alter_user_lnames_alter_user_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='run',
            field=models.CharField(default=12312, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
