# Generated by Django 5.0.6 on 2024-07-15 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
