# Generated by Django 4.2.11 on 2024-07-13 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id_brand', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_brand', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_product', models.CharField(max_length=200)),
                ('stock_product', models.IntegerField()),
                ('price_product', models.IntegerField()),
                ('timestamp_product', models.DateTimeField()),
                ('id_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.brand')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.product')),
            ],
        ),
    ]
