# Generated by Django 5.0.6 on 2024-07-14 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_category',
            name='id_brand',
        ),
        migrations.AddField(
            model_name='product_category',
            name='id_category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='product_management.category'),
            preserve_default=False,
        ),
    ]
