# Generated by Django 5.0.6 on 2024-07-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0002_remove_product_category_id_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_product',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
